# Generated by Django 5.0.3 on 2024-03-05 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d12c1a91-c86a-4f93-895f-0d96ee0db778'), primary_key=True, serialize=False, unique=True),
        ),
    ]
