# Generated by Django 5.0.3 on 2024-03-05 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca92d3c4-3422-4348-aa89-a3e36c17f8b1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
