# Generated by Django 5.0.3 on 2024-03-06 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eca5b2f2-db60-4c0e-8bd5-2c70a90878c2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
