# Generated by Django 5.0.3 on 2024-03-08 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ff44c84-b500-449f-b3db-e65b74bb6315'), primary_key=True, serialize=False, unique=True),
        ),
    ]
