# Generated by Django 5.0.3 on 2024-03-14 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a44821e5-b9e1-4ad5-ab7c-a2c9edbb5bcd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
