# Generated by Django 5.0.3 on 2024-03-16 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bb0aa15-d0b4-4901-83e8-fe2e6777c297'), primary_key=True, serialize=False, unique=True),
        ),
    ]
