# Generated by Django 5.0.3 on 2024-03-23 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f458129-57c4-44e2-abf2-35129aa577d6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
