# Generated by Django 4.2.6 on 2024-03-23 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c73a1e4d-5dfd-4b65-9835-c4a00dd3a30e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
