# Generated by Django 4.2.6 on 2024-03-23 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3a05491-357c-44c8-939c-d8945327d3dc'), primary_key=True, serialize=False, unique=True),
        ),
    ]
