# Generated by Django 4.2.6 on 2024-03-30 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9af43b21-04b4-42a6-9b90-1c1051704e9c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
