# Generated by Django 4.2.6 on 2024-03-31 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3981259c-cda3-4933-85a1-425320a077e7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
