# Generated by Django 4.2.6 on 2024-03-31 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f2c3bbe-8544-483e-9f43-ecd90481e65f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
