# Generated by Django 4.2.6 on 2024-03-31 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b3373a6-67d9-4eb1-98e5-b6229bb80450'), primary_key=True, serialize=False, unique=True),
        ),
    ]
