# Generated by Django 5.0.3 on 2024-03-06 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField(null=True, verbose_name='description')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('website', models.URLField(default='https://cataloguez.com')),
                ('fb', models.URLField(default='https://www.facebook.com', verbose_name='Facebook')),
                ('ig', models.URLField(default='https://www.instagram.com/', verbose_name='Instagram')),
                ('x', models.URLField(default='https://www.X.com/', verbose_name='X')),
                ('pt', models.URLField(default='https://www.pinterest.com/', verbose_name='Pinterest')),
                ('maps_url', models.URLField(default='https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Chief Executive Officer', 'Chief Executive Officer'), ('Chief Marketing Officer', 'Chief Marketing Officer'), ('Accounting Executive', 'Accounting Executive'), ('Creative Art Director #C69', 'Creative Art Director #C69')], max_length=200)),
                ('desc', models.CharField(max_length=300, verbose_name='description')),
                ('avatar', models.ImageField(upload_to='team/')),
                ('fb', models.URLField(default='https://www.facebook.com', verbose_name='Facebook')),
                ('x', models.URLField(default='https://www.X.com/', verbose_name='X')),
                ('ln', models.URLField(default='https://www.linkedin.com/', verbose_name='Linkedin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
