# Generated by Django 5.0.3 on 2024-03-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tag',
            new_name='tags',
        ),
    ]
