# Generated by Django 5.0.3 on 2024-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_tag_photo_tags_rename_tag_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
