# Generated by Django 5.0.3 on 2024-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_photo_format_video_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
