# Generated by Django 5.0.3 on 2024-03-16 13:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_photo_views_video_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-views']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-views']},
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
