# Generated by Django 4.2.6 on 2024-03-30 21:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=models.CharField(max_length=300)),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=models.CharField(max_length=300)),
        ),
    ]
